# Kafka Manager Configuration
spring.application.name=kafka-manager
server.port=8085
  
  # Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/kafka_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=kafka_user
spring.datasource.password=kafka_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
  
  # Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=kafka-manager-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
  
  # Kafka Admin Configuration
kafka.admin.bootstrap-servers=localhost:9092
kafka.admin.client-id=kafka-manager-admin
  
  # WebSocket Configuration
spring.websocket.path=/ws
spring.websocket.allowed-origins=*
  
  # Logging Configuration
logging.level.com.kafka.kafka=INFO
logging.level.org.apache.kafka=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
  
  # Management Endpoints
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.info.enabled=true
  
  # Native Image Configuration
spring.aot.enabled=true
spring.native.build-args=--initialize-at-build-time=org.apache.kafka
