# Spring Boot Admin Configuration
spring:
  application:
    name: spring-boot-admin
  
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/admin_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin_user
    password: admin_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  # Admin Server Configuration
  boot:
    admin:
      server:
        context-path: /
        monitor:
          period: 10s
          status-lifetime: 10s
          info-lifetime: 1m
  
  # Security Configuration
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN
  
  # Native Image Configuration
  aot:
    enabled: true
  native:
    build-args: "--initialize-at-build-time=org.springframework.boot.admin"

server:
  port: 8080

# Logging Configuration
logging:
  level:
    com.kafka.admin: INFO
    de.codecentric.boot.admin: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
    metrics:
      enabled: true
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      service: spring-boot-admin
      application: ${spring.application.name}
  info:
    env:
      enabled: true