# Spring Boot Admin Configuration
spring.application.name=spring-boot-admin
server.port=8080
  
  # Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/admin_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=admin_user
spring.datasource.password=admin_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
  
  # Admin Server Configuration
spring.boot.admin.server.context-path=/
spring.boot.admin.server.monitor.period=10s
spring.boot.admin.server.monitor.status-lifetime=10s
spring.boot.admin.server.monitor.info-lifetime=1m
  
  # Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN
  
  # Logging Configuration
logging.level.com.kafka.admin=INFO
logging.level.de.codecentric.boot.admin=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
  
  # Management Endpoints
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.info.enabled=true
management.info.env.enabled=true
  
  # Native Image Configuration
spring.aot.enabled=true
spring.native.build-args=--initialize-at-build-time=org.springframework.boot.admin
